exclude_paths:
    - 'bin/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/*'
    - 'log/*'
    - 'node_modules/*'
    - 'public/*'
    - 'storage/*'
    - 'test/**/*.rb'
    - 'tmp/*'
    - 'vendor/*'
    - 'spec/**/*.rb'
directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
