Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/*'
    - 'log/*'
    - 'node_modules/**/**'
    - 'public/*'
    - 'storage/*'
    - 'test/**/*.rb'
    - 'tmp/*'
    - 'vendor/*'
    - 'babel.config.js'
    - 'config.ru'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'spec/**/*.rb'
