language: ruby
rvm:
  - 3.0.0
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
  - redis-server
before_script:
  - bundle install
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
